export enum UtilityType {
  ELECTRICITY = 'ELECTRICITY',
  WATER = 'WATER',
  GAS = 'GAS',
  DG_POWER = 'DG_POWER',
  SOLAR = 'SOLAR',
  RECYCLED_WATER = 'RECYCLED_WATER',
  SEWAGE = 'SEWAGE',
  OTHER = 'OTHER',
}

export enum UtilityStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum UtilitySourceType {
  GRID = 'GRID',
  MUNICIPAL = 'MUNICIPAL',
  BOREWELL = 'BOREWELL',
  TANKER = 'TANKER',
  DG = 'DG',
  SOLAR = 'SOLAR',
  STP = 'STP',
  WTP = 'WTP',
  GAS_SUPPLIER = 'GAS_SUPPLIER',
  OTHER = 'OTHER',
}

export enum UtilityMeterType {
  MAIN = 'MAIN',
  SUB_METER = 'SUB_METER',
  CHECK_METER = 'CHECK_METER',
  GENERATION_METER = 'GENERATION_METER',
  IMPORT_METER = 'IMPORT_METER',
  EXPORT_METER = 'EXPORT_METER',
  FLOW_METER = 'FLOW_METER',
  VIRTUAL = 'VIRTUAL',
  OTHER = 'OTHER',
}

export enum MeasurementType {
  ENERGY = 'ENERGY',
  ACTIVE_ENERGY = 'ACTIVE_ENERGY',
  APPARENT_ENERGY = 'APPARENT_ENERGY',
  DEMAND = 'DEMAND',
  WATER_VOLUME = 'WATER_VOLUME',
  GAS_VOLUME = 'GAS_VOLUME',
  FLOW = 'FLOW',
  LEVEL = 'LEVEL',
  GENERATION = 'GENERATION',
  FUEL_VOLUME = 'FUEL_VOLUME',
  OTHER = 'OTHER',
}

export enum UtilityMeterStatus {
  REGISTERED = 'REGISTERED',
  INSTALLED = 'INSTALLED',
  ACTIVE = 'ACTIVE',
  FAULTY = 'FAULTY',
  UNDER_TEST = 'UNDER_TEST',
  SUSPENDED = 'SUSPENDED',
  REPLACED = 'REPLACED',
  DECOMMISSIONED = 'DECOMMISSIONED',
  ARCHIVED = 'ARCHIVED',
}

export enum MeterAssignmentTargetType {
  COMMUNITY = 'COMMUNITY',
  SECTION = 'SECTION',
  BUILDING = 'BUILDING',
  FLOOR = 'FLOOR',
  UNIT = 'UNIT',
  AMENITY = 'AMENITY',
  COMMON_AREA = 'COMMON_AREA',
  ASSET = 'ASSET',
  UTILITY_NODE = 'UTILITY_NODE',
  OTHER = 'OTHER',
}

export enum MeterReadingType {
  ACTUAL = 'ACTUAL',
  ESTIMATED = 'ESTIMATED',
  OPENING = 'OPENING',
  CLOSING = 'CLOSING',
  REPLACEMENT_FINAL = 'REPLACEMENT_FINAL',
  REPLACEMENT_OPENING = 'REPLACEMENT_OPENING',
  CORRECTION = 'CORRECTION',
  RESET = 'RESET',
  ROLLOVER = 'ROLLOVER',
  OTHER = 'OTHER',
}

export enum MeterReadingSource {
  MANUAL = 'MANUAL',
  MOBILE = 'MOBILE',
  CSV_IMPORT = 'CSV_IMPORT',
  XLSX_IMPORT = 'XLSX_IMPORT',
  API = 'API',
  IOT_GATEWAY = 'IOT_GATEWAY',
  SMART_METER = 'SMART_METER',
  BMS = 'BMS',
  SCADA = 'SCADA',
  OTHER = 'OTHER',
}

export enum MeterReadingStatus {
  RECEIVED = 'RECEIVED',
  VALIDATING = 'VALIDATING',
  VALID = 'VALID',
  WARNING = 'WARNING',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  SUPERSEDED = 'SUPERSEDED',
  CORRECTED = 'CORRECTED',
}

export enum MeterReadingQuality {
  GOOD = 'GOOD',
  ESTIMATED = 'ESTIMATED',
  SUSPECT = 'SUSPECT',
  MISSING = 'MISSING',
  DEVICE_ERROR = 'DEVICE_ERROR',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}

export enum TariffStatus {
  DRAFT = 'DRAFT',
  UNDER_APPROVAL = 'UNDER_APPROVAL',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  SUPERSEDED = 'SUPERSEDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum TariffComponentType {
  FIXED = 'FIXED',
  PER_UNIT = 'PER_UNIT',
  SLAB = 'SLAB',
  MINIMUM = 'MINIMUM',
  DEMAND = 'DEMAND',
  TIME_OF_USE = 'TIME_OF_USE',
  FUEL_SURCHARGE = 'FUEL_SURCHARGE',
  SERVICE_CHARGE = 'SERVICE_CHARGE',
  ADJUSTMENT = 'ADJUSTMENT',
  TAX_METADATA = 'TAX_METADATA',
  OTHER = 'OTHER',
}

export enum UtilityChargeStatus {
  DRAFT = 'DRAFT',
  VALIDATED = 'VALIDATED',
  APPROVED = 'APPROVED',
  HANDED_OFF = 'HANDED_OFF',
  ADJUSTED = 'ADJUSTED',
  CANCELLED = 'CANCELLED',
}

export enum UtilityOutageType {
  PLANNED = 'PLANNED',
  UNPLANNED = 'UNPLANNED',
  SUPPLIER_OUTAGE = 'SUPPLIER_OUTAGE',
  INTERNAL_FAULT = 'INTERNAL_FAULT',
  MAINTENANCE = 'MAINTENANCE',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}

export enum UtilityOutageStatus {
  REPORTED = 'REPORTED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  RESTORED = 'RESTORED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum WaterTankerStatus {
  EXPECTED = 'EXPECTED',
  ARRIVED = 'ARRIVED',
  VERIFIED = 'VERIFIED',
  ACCEPTED = 'ACCEPTED',
  PARTIALLY_ACCEPTED = 'PARTIALLY_ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum UtilityAnomalyType {
  CONSUMPTION_SPIKE = 'CONSUMPTION_SPIKE',
  CONSUMPTION_DROP = 'CONSUMPTION_DROP',
  ZERO_CONSUMPTION = 'ZERO_CONSUMPTION',
  METER_STUCK = 'METER_STUCK',
  NEGATIVE_DELTA = 'NEGATIVE_DELTA',
  BALANCE_VARIANCE = 'BALANCE_VARIANCE',
  POSSIBLE_WATER_LOSS = 'POSSIBLE_WATER_LOSS',
  ENERGY_LOSS_HIGH = 'ENERGY_LOSS_HIGH',
  DG_EFFICIENCY_LOW = 'DG_EFFICIENCY_LOW',
  TANKER_QUANTITY_VARIANCE = 'TANKER_QUANTITY_VARIANCE',
  QUALITY_RESULT_WARNING = 'QUALITY_RESULT_WARNING',
  OTHER = 'OTHER',
}

export enum UtilityAnomalyStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CONFIRMED = 'CONFIRMED',
  FALSE_POSITIVE = 'FALSE_POSITIVE',
  RESOLVED = 'RESOLVED',
  IGNORED_WITH_REASON = 'IGNORED_WITH_REASON',
}

export enum SustainabilityTargetStatus {
  ON_TRACK = 'ON_TRACK',
  AT_RISK = 'AT_RISK',
  OFF_TRACK = 'OFF_TRACK',
  ACHIEVED = 'ACHIEVED',
  NOT_EVALUATED = 'NOT_EVALUATED',
}

export enum BalanceCompletenessStatus {
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',
}
